title: Rachel Yamamoto
author: Rachel Yamamoto
description: Rachel's website

show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false


navigation:
  - {file: "README.md", title: "About", icon: address-card}

theme: jekyll-theme-midnight
plugins:
  - jekyll-freed
