title: Rachel Yamamoto
author: Rachel Yamamoto
description: Rachel's website

show_social: false
show_excerpts: false
show_frame: false
show_sidebar: false

nav-barlinks:
  About Me: "about me"
  Author's home: "https://reysachi.github.io/"
  
exclude:
  - README.md

theme: jekyll-theme-midnight
plugins:
  - jekyll-freed
