title: Rachel Yamamoto
author: Rachel Yamamoto
description: Rachel's website

show_social: true
show_excerpts: false
show_frame: false
show_sidebar: true


navigation:
  - {file: "README.md", title: "About", icon: address-card}
  - {title: "Resume", url: "https://reysachi.github.io/jekyll-resume/"}

theme: jekyll-theme-midnight
plugins:
  - jekyll-freed
