title: Rachel Yamamoto
author: Rachel Yamamoto
description: Rachel's website

navbar-links:
  About Me: "about me"
  Author's home: "https://reysachi.github.io/"
  

theme: jekyll-theme-midnight
plugins:
  - jekyll-freed
